version: "3.9"

services:
  server:
    build: ./server
    ports:
      - ${SERVER_PORTS}
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - JWT_SECRET=${JWT_SECRET}
      - EXPIRES_IN=${EXPIRES_IN}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - ${FRONTEND_PORTS}

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORTS}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
