version: "3.9"

services:
  server:
    build: ./server
    ports:
      - ${SERVER_PORTS}
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - ${FRONTEND_PORTS}

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORTS}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
